const express = require('express')
const router = express.Router()
const BarberoController = require('../controllers/barbero.controller')
const validateRequest = require('../middlewares/validateRequest')
const { BarberoSchema } = require('../../../infraestructure/schemas/barbero.schema')

router.post('/', validateRequest({ body: BarberoSchema }), BarberoController.crear)
router.get('/', BarberoController.obtenerTodos)
router.get('/especialidad/:especialidad', BarberoController.buscarPorEspecialidad)
router.get('/email/:email', BarberoController.obtenerPorEmail)
router.get('/:id', BarberoController.obtenerPorId)
router.get('/:id/stats', BarberoController.obtenerStats)
router.get('/:id/citas', BarberoController.obtenerCitas)
router.get('/:id/servicios', BarberoController.obtenerServicios)
router.post('/:id/servicios', BarberoController.agregarServicio)
router.delete('/:id/servicios/:id_servicio', BarberoController.eliminarServicio)
router.get('/:id/disponibilidad', BarberoController.obtenerDisponibilidad)
router.get('/:id/disponibilidad/:fecha', BarberoController.obtenerDisponibilidad)
router.put('/:id', validateRequest({ body: BarberoSchema.partial() }), BarberoController.actualizar)
router.put('/:id/horario', BarberoController.actualizarHorario)
router.delete('/:id', BarberoController.eliminar)
router.post('/:id/foto', BarberoController.actualizarFoto)

module.exports = router